### ISSUE TITLE
up-to-date API

### ISSUE THREAD

**Issue by dimov-cz** [crealytics/adscriptor#5]
Hi, where can i get more uptodate AdWordsApi.json? There are some significant differences in current version.

Thanks

**Comment by Turtlefight** [comment]
Hi dimov-cz, i'll update the AdWordsApi.json in the next hours, thanks for reporting this :)

**Comment by Turtlefight** [comment]
Hi dimov-cz, i updated the API to the newest AdWordsApi Version.
All optional APIs (Youtube, ContentApi, etc..) were also updated to their latest versions.

Thanks for bringing this to our attention :)
Have a nice evening,
Sven

**Comment by dimov-cz** [comment]
Thanks for superfast response, have a nice day.
